/**
 * The 20 fictional listings that make up the Hera exchange.
 *
 * Each company carries the parameters the simulation engine needs: a starting
 * price, per-tick volatility, a long-run drift (its growth story), a beta that
 * controls how strongly it tracks the index, and a dividend yield. Names and
 * tickers are invented; any resemblance to real issuers is coincidental.
 */
export const SECTORS = [
  'Technology',
  'Energy',
  'Healthcare',
  'Finance',
  'Consumer',
  'Industrials',
  'Materials',
  'Entertainment',
] as const;

export type Sector = (typeof SECTORS)[number];

export const SECTOR_BETA: Record<string, number> = {
  Technology: 1.35,
  Energy: 0.95,
  Healthcare: 0.75,
  Finance: 1.1,
  Consumer: 0.9,
  Industrials: 1.05,
  Materials: 0.85,
  Entertainment: 1.25,
};

export interface CompanySeed {
  symbol: string;
  name: string;
  sector: string;
  description: string;
  price: number;
  volatility: number;
  drift: number;
  beta: number;
  sharesOutstanding: number;
  dividendYield?: number;
}

export const COMPANIES: CompanySeed[] = [
  {
    symbol: 'NOVA',
    name: 'Novadyne Systems',
    sector: 'Technology',
    description: 'Enterprise AI infrastructure and datacentre accelerators.',
    price: 412.5,
    volatility: 0.021,
    drift: 0.0016,
    beta: 1.45,
    sharesOutstanding: 1_800_000_000,
    dividendYield: 0.0,
  },
  {
    symbol: 'QBTX',
    name: 'Qubitix Labs',
    sector: 'Technology',
    description: 'Quantum compute research and cryogenic hardware.',
    price: 88.2,
    volatility: 0.034,
    drift: 0.0021,
    beta: 1.7,
    sharesOutstanding: 640_000_000,
  },
  {
    symbol: 'HLIX',
    name: 'Helix Forge',
    sector: 'Technology',
    description: 'Developer tooling and cloud-native build pipelines.',
    price: 245.75,
    volatility: 0.018,
    drift: 0.0012,
    beta: 1.25,
    sharesOutstanding: 1_100_000_000,
    dividendYield: 0.004,
  },
  {
    symbol: 'ARCD',
    name: 'Arcadia Networks',
    sector: 'Technology',
    description: 'Undersea fibre and metro mesh networking gear.',
    price: 63.4,
    volatility: 0.024,
    drift: 0.0008,
    beta: 1.15,
    sharesOutstanding: 900_000_000,
    dividendYield: 0.011,
  },
  {
    symbol: 'PYRA',
    name: 'Pyravolt Energy',
    sector: 'Energy',
    description: 'Grid-scale battery storage and inverter systems.',
    price: 154.9,
    volatility: 0.028,
    drift: 0.0014,
    beta: 1.1,
    sharesOutstanding: 520_000_000,
  },
  {
    symbol: 'TERA',
    name: 'Terrafirma Fuels',
    sector: 'Energy',
    description: 'Conventional drilling with a legacy pipeline network.',
    price: 47.15,
    volatility: 0.019,
    drift: 0.0002,
    beta: 0.85,
    sharesOutstanding: 2_400_000_000,
    dividendYield: 0.048,
  },
  {
    symbol: 'SOLR',
    name: 'Solaris Reach',
    sector: 'Energy',
    description: 'Utility-scale solar farms across three continents.',
    price: 72.6,
    volatility: 0.026,
    drift: 0.0011,
    beta: 1.05,
    sharesOutstanding: 780_000_000,
    dividendYield: 0.018,
  },
  {
    symbol: 'MEDI',
    name: 'Medivance Pharma',
    sector: 'Healthcare',
    description: 'Oncology pipeline and specialty therapeutics.',
    price: 198.3,
    volatility: 0.023,
    drift: 0.0009,
    beta: 0.8,
    sharesOutstanding: 610_000_000,
    dividendYield: 0.021,
  },
  {
    symbol: 'GENX',
    name: 'Geneworks Bio',
    sector: 'Healthcare',
    description: 'Gene-editing platforms and clinical trial services.',
    price: 34.85,
    volatility: 0.041,
    drift: 0.0018,
    beta: 1.35,
    sharesOutstanding: 430_000_000,
  },
  {
    symbol: 'VITA',
    name: 'Vitaline Health',
    sector: 'Healthcare',
    description: 'Outpatient clinic chains and remote monitoring devices.',
    price: 112.45,
    volatility: 0.016,
    drift: 0.0007,
    beta: 0.7,
    sharesOutstanding: 1_300_000_000,
    dividendYield: 0.027,
  },
  {
    symbol: 'AURE',
    name: 'Aurelia Capital',
    sector: 'Finance',
    description: 'Mid-market investment banking and advisory.',
    price: 286.1,
    volatility: 0.017,
    drift: 0.0008,
    beta: 1.2,
    sharesOutstanding: 700_000_000,
    dividendYield: 0.032,
  },
  {
    symbol: 'LEDG',
    name: 'Ledgerstone Bank',
    sector: 'Finance',
    description: 'Regional retail banking and mortgage lending.',
    price: 58.7,
    volatility: 0.014,
    drift: 0.0004,
    beta: 0.95,
    sharesOutstanding: 2_100_000_000,
    dividendYield: 0.042,
  },
  {
    symbol: 'MINT',
    name: 'Mintcoin Exchange',
    sector: 'Finance',
    description: 'Digital asset custody and settlement rails.',
    price: 23.95,
    volatility: 0.052,
    drift: 0.0013,
    beta: 1.85,
    sharesOutstanding: 380_000_000,
  },
  {
    symbol: 'BREW',
    name: 'Brewster Provisions',
    sector: 'Consumer',
    description: 'Packaged foods and beverage distribution.',
    price: 76.25,
    volatility: 0.012,
    drift: 0.0005,
    beta: 0.65,
    sharesOutstanding: 1_500_000_000,
    dividendYield: 0.035,
  },
  {
    symbol: 'STYL',
    name: 'Stylus Apparel',
    sector: 'Consumer',
    description: 'Direct-to-consumer fashion and licensed sportswear.',
    price: 41.6,
    volatility: 0.025,
    drift: 0.0006,
    beta: 1.0,
    sharesOutstanding: 820_000_000,
    dividendYield: 0.014,
  },
  {
    symbol: 'FRST',
    name: 'Firstlight Retail',
    sector: 'Consumer',
    description: 'Grocery and general merchandise superstore chain.',
    price: 129.8,
    volatility: 0.015,
    drift: 0.0006,
    beta: 0.75,
    sharesOutstanding: 1_050_000_000,
    dividendYield: 0.019,
  },
  {
    symbol: 'TITN',
    name: 'Titanworks Heavy',
    sector: 'Industrials',
    description: 'Earthmoving equipment and mining haul trucks.',
    price: 214.35,
    volatility: 0.022,
    drift: 0.0009,
    beta: 1.15,
    sharesOutstanding: 480_000_000,
    dividendYield: 0.023,
  },
  {
    symbol: 'RAIL',
    name: 'Railcore Logistics',
    sector: 'Industrials',
    description: 'Freight rail corridors and intermodal terminals.',
    price: 93.55,
    volatility: 0.017,
    drift: 0.0006,
    beta: 0.9,
    sharesOutstanding: 950_000_000,
    dividendYield: 0.029,
  },
  {
    symbol: 'COPR',
    name: 'Copperfield Metals',
    sector: 'Materials',
    description: 'Copper and rare-earth extraction and refining.',
    price: 167.4,
    volatility: 0.027,
    drift: 0.0007,
    beta: 1.05,
    sharesOutstanding: 540_000_000,
    dividendYield: 0.026,
  },
  {
    symbol: 'PIXL',
    name: 'Pixelbound Studios',
    sector: 'Entertainment',
    description: 'Game publishing and interactive streaming IP.',
    price: 51.3,
    volatility: 0.038,
    drift: 0.0015,
    beta: 1.4,
    sharesOutstanding: 600_000_000,
  },
];

export const COMPANIES_BY_SYMBOL: Record<string, CompanySeed> = Object.fromEntries(
  COMPANIES.map((company) => [company.symbol, company]),
);
